apiVersion: v1
kind: Pod
metadata:
  name: doc-pod
spec:
  containers:
    - name: doc-pod
      image: doc:v1.0.0
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "100m"
          memory: "250Mi"
        requests:
          cpu: "10m"
          memory: "50Mi"
