apiVersion: batch/v1
kind: Job
metadata:
  name: job-job
spec:
  template:
    spec:
      containers:
        - name: job-job
          image: job:v1.0.0
      resources:
        resources:
        limits:
          cpu: "200m"
          memory: "500Mi"
        requests:
          cpu: "200m"
          memory: "500Mi"
      restartPolicy: Never
  parallelism: 1
