apiVersion: v1
kind: Pod
metadata:
  name: doc-pod
spec:
  containers:
    - name: doc-pod
      image: doc:v1.0.0
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "100m"
          memory: "250Mi"
        requests:
          cpu: "10m"
          memory: "50Mi"
      volumeMounts:
        - mountPath: "/srv"
          name: doc-pod-vol
  volumes:
    - name: doc-pod-vol
      ephemeral:
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            storageClassName: doc-pod-class
            resources:
              requests:
                storage: 1Gi
